### ISSUE TITLE
Long username messes up top navbar

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#258]
Noticed this when working on #14.

![Screenshot 2021-06-12 at 21-51-01 simpleimage - Simple Image Upload](https://user-images.githubusercontent.com/3276350/121793524-f5f2db00-cbcd-11eb-94db-98077b7ef7be.png)

The button that displays your username appears to expand out and mess up the top navbar. Username should be cropped out somehow, or made smaller. A username limit would also be nice.

**Comment by mayankbucha** [comment]
Hi @Coteh, 
I would like to solve this issue. 
I think username should be limited to 24 chars. As, it would also be good for mobile view also.

**Comment by Coteh** [comment]
Go for it. :)

Also, perhaps set username limit as a config variable (set via environment variable) in case I want to increase the limit in the future.
