### ISSUE TITLE
Delete images prompt is not centered

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#278]
<img width="679" alt="Screen Shot 2021-07-24 at 7 18 46 PM" src="https://user-images.githubusercontent.com/3276350/126883597-b01abf06-fac7-48cc-ac08-af6fb75bbcb8.png">
<img width="491" alt="Screen Shot 2021-07-24 at 7 18 19 PM" src="https://user-images.githubusercontent.com/3276350/126883594-76091cca-dcdd-4e6f-8131-90dcaeedf349.png">

These two prompts (confirm and failure respectively) - and possibly the success one as well - are not centered. They should be centered on the page.

**Comment by alvarotorrestx** [comment]
Hi can I be assigned/try and assist with this please?

**Comment by Coteh** [comment]
Hey @alvarotorrestx go for it! :D
