### ISSUE TITLE
Add endpoint to grab a lower quality version of the image

### ISSUE THREAD

**Issue by Coteh** [Coteh/simpleimage#289]
Split from #13. Add an endpoint (or add it as a param to existing /images endpoint) to allow for a lower quality or smaller dimension version of the image to be returned. This would be used for things such as User Images section in user profile or Comments section in user profile (currently being worked on in #13), to allow for more images to be loaded at once with less bandwidth transferred overall. (user may only be interested in a few of these images, thus they don't need to be loaded in perfect quality)

Consider caching the lower quality images as well for future requests.

**Comment by mayankbucha** [comment]
Hi @Coteh, shall I take this one next?

**Comment by Coteh** [comment]
Yep you can take it. :)

**Comment by mayankbucha** [comment]
Shall we use `sharp` npm package to lower down the image size?
[https://www.npmjs.com/package/sharp](https://www.npmjs.com/package/sharp)

**Comment by Coteh** [comment]
Yup that package should work for what we’re trying to do.

**Comment by mayankbucha** [comment]
Should we integrate this functionality on the route `"/images/:id.:ext"` by providing the optional param as 
`"/images/:id.:ext/low-res?"`  to get the low resolution image?

**Comment by Coteh** [comment]
Yeah but make it a query parameter instead of a subroute. e.g. :image.:ext?res=low and that’d probably be good.

**Comment by mayankbucha** [comment]
Currently, when rendering the image-view from url `"/images/:id/"`, I am appending the query string to the id of the image.
```
 res.render("image-view", {
      id,
      imageSrc: id + "." + util.mimeTypeToExt(imageEntry[0].mimetype) +"?res=low",
      uploadedDate: imageEntry[0].uploadeddate || "Unknown Date",
      author: imageEntry[0].username,
      user: sessionObj.user
});
```
Then I am extracting `res=low` query in the url `"/images/:id.:ext"` and then performing the image operations.
Is this the right way?

**Comment by Coteh** [comment]
I think for the purposes of this particular change, just extracting it on the `/images/:id.:ext` route is enough. We can add low quality as an option for the image page at a later point.
